export const BRAND = {
    name: "Jevon Ashley",
    headline: "AI Builder • Software Engineering Student • Creative Technologist",
    subheadline: "Building AI-powered platforms, digital experiences, intelligent workflows, and modern automation systems.",
    mission: "Combine AI, software engineering, cloud learning, automation, and creative technology into scalable modern platforms.",
    mainBrand: "VidVisionsAI",
    domain: "https://www.vidvisionsai.pro",
};

export const PROJECTS = [
  {
        id: "ai-dimensions",
        title: "AI Dimensions",
        description: "Photo-to-blueprint studio. Turn photos into interactive, editable diagrams with AI vectorization, canvas editing, layers, and SVG/PDF/DXF export.",
        url: "https://aidimensions.online",
        tags: ["AI Systems", "Vision", "SaaS"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Faidimensions.online?w=800",
  },
  {
        id: "roadops-ai",
        title: "RoadOps AI",
        description: "Truck-first trip intelligence and trucking operations platform with controlled-access fleet workflows.",
        url: "https://www.roadopsai.pro",
        tags: ["AI Systems", "Logistics", "SaaS"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.roadopsai.pro?w=800",
  },
  {
        id: "apex-inventory",
        title: "Apex Inventory AI",
        description: "AI-powered demand forecasting, automated reorder execution, and live margin-risk visibility for inventory operations.",
        url: "https://apexinventoryai.online",
        tags: ["SaaS", "Automation", "AI Systems"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fapexinventoryai.online?w=800",
  },
  {
        id: "invoiceos",
        title: "InvoiceOS AI",
        description: "AI business operating system for small businesses — professional invoicing, Stripe Connect payments, automated follow-ups, and real-time revenue reports.",
        url: "https://invoicechaser.org",
        tags: ["SaaS", "Fintech", "Automation"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Finvoicechaser.org?w=800",
  },
  {
        id: "repoflow-ai",
        title: "RepoFlow AI",
        description: "AI-powered vehicle repossession, collateral recovery, and lender visibility platform built for the modern repo industry.",
        url: "https://repoflowai.online",
        tags: ["SaaS", "AI Systems", "Fintech"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Frepoflowai.online?w=800",
  },
  {
        id: "littlelog",
        title: "LittleLog",
        description: "All-in-one childcare center management — real-time attendance, ratio compliance, automated Stripe billing, and a dedicated parent portal.",
        url: "https://littlelog.online",
        tags: ["SaaS", "EdTech", "Automation"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Flittlelog.online?w=800",
  },
  {
        id: "smart-slots",
        title: "Smart Slots",
        description: "High-performance, commission-free booking protocol for professional studios — elevating the scheduling experience.",
        url: "https://smartslot4u.online",
        tags: ["SaaS", "Booking", "Automation"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fsmartslot4u.online?w=800",
  },
  {
        id: "diy-genius",
        title: "DIY Genius AI",
        description: "AI-powered DIY platform generating step-by-step instructions, interactive workflows, videos, and troubleshooting guides for any project.",
        url: "https://diygenius.online",
        tags: ["AI Systems", "SaaS", "Consumer"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fdiygenius.online?w=800",
  },
  {
        id: "build-catalyst",
        title: "Build Catalyst",
        description: "Internal AI operations hub — run automated business audits, surface automation opportunities, and manage sub-brands from one command center.",
        url: "https://www.buildateam.online",
        tags: ["AI Systems", "Automation", "Business"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.buildateam.online?w=800",
  },
  {
        id: "the-wet-spot",
        title: "The Wet Spot",
        description: "Next-generation creator monetization ecosystem — subscriptions, live tipping, messaging, and digital products engineered to keep creators' revenue.",
        url: "https://www.thewetspot.space",
        tags: ["Ecosystem", "Creator Economy", "SaaS"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.thewetspot.space?w=800",
  },
  {
        id: "red-or-blue-pill",
        title: "Red or Blue Pill",
        description: "Dark-themed conversion sales page for the book 'Awakening to Your True Frequency' with Stripe checkout and email delivery.",
        url: "https://awakenredorblue.online",
        tags: ["Creative", "Publishing", "E-commerce"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fawakenredorblue.online?w=800",
  },
  {
        id: "silverfoxx2u",
        title: "SilverFoxx2u",
        description: "Immersive artist experience for THE FOXX — cinematic video backdrops, Spotify integration, and a fan mailing list, straight from McComb, Mississippi.",
        url: "https://silverfoxx2u.online",
        tags: ["Creative", "Music", "Media"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fsilverfoxx2u.online?w=800",
  },
  {
        id: "captured-by-cashmere",
        title: "Captured by Cashmere",
        description: "Premium photography and creative media platform showcasing high-end visual storytelling.",
        url: "https://www.capturedbycashmere.pro",
        tags: ["Creative", "Media", "Photography"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.capturedbycashmere.pro?w=800",
  },
  {
        id: "ascend",
        title: "Ascend (Vibrate Higher)",
        description: "Identity-based habit RPG — habits become XP-bearing quests that level up the person you're becoming.",
        url: "https://www.vibratehigher.online",
        tags: ["Ecosystem", "Wellness", "Consumer"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fwww.vibratehigher.online?w=800",
  },
  {
        id: "prettyneverything",
        title: "PrettyNeverything",
        description: "Premium DTF printing studio with a live design tool — upload artwork, preview it on garments, and order custom prints, gang sheets, and bulk runs.",
        url: "https://prettyneverything.online",
        tags: ["E-commerce", "Creative", "Business"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fprettyneverything.online?w=800",
  },
  {
        id: "revival-renovations",
        title: "Revival Renovations",
        description: "Premium home restoration and design portfolio with an interactive cost estimator, client reviews, and consultation booking.",
        url: "https://revivalrenovationrepair.online",
        tags: ["Business", "Construction", "Booking"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Frevivalrenovationrepair.online?w=800",
  },
  {
        id: "first-unity-federal",
        title: "First Unity Federal",
        description: "Digital member portal for a Mississippi credit union — dynamic loan calculators, live rate tables, and streamlined membership applications.",
        url: "https://firstunityfederal.online",
        tags: ["Business", "Fintech", "Community"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Ffirstunityfederal.online?w=800",
  },
  {
        id: "big-ds-tires",
        title: "Big D's Tire & Auto",
        description: "Interactive automotive hub for McComb's trusted tire shop — 3D tire renderer, full service catalog, and instant-call booking.",
        url: "https://bigdtireshop.online",
        tags: ["Business", "Automotive", "Local"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fbigdtireshop.online?w=800",
  },
  {
        id: "bellas-kitchen",
        title: "Bella's Meals on Wheels",
        description: "Premium interactive food truck site for Bella's Kitchen — southern comfort menus with online ordering in a hot pink and black aesthetic.",
        url: "https://bellasmealsonwheels.online",
        tags: ["Business", "Food", "E-commerce"],
        image: "https://s0.wp.com/mshots/v1/https%3A%2F%2Fbellasmealsonwheels.online?w=800",
  },
  ];

export const EDUCATION = [
  {
        institution: "Western Governors University",
        degree: "B.S. Software Engineering (In Progress)",
        description: "Expected 2028. Full-stack development, cloud architecture, and modern engineering principles.",
  },
  {
        institution: "Southwest Mississippi Community College",
        degree: "A.S. Process Operations Technology",
        description: "GPA 3.8, Summa Cum Laude. Foundational training in technical systems and operational efficiency.",
  },
  ];

export const LINKS = {
    microsoftLearn: "https://learn.microsoft.com/en-us/users/javonashley-9359/",
    email: "jvnashley@gmail.com",
    phone: "(601) 341-3901",
    github: "https://github.com/cashmereu3-dev",
    linkedin: "https://www.linkedin.com/in/jevon-ashley-75183a409",
    reel: "/reel/",
    resumePdf: "/Jevon_Ashley_Resume.pdf",
};

export const TECH_STACK = [
    "React", "TypeScript", "Node.js", "Python", "Cloud (Azure/AWS)", "Microsoft 365 Copilot", "Generative AI", "Automation", "SaaS Architecture"
  ];
